// The CUDA backend: runs the kernels of cpp/cuda/kernels.cu on an NVIDIA GPU with the CPU's bits.
//
// Nothing CUDA is needed to build the extension. At run time the CUDA driver (nvcuda.dll / libcuda.so.1, part of
// the NVIDIA driver) and NVRTC (the CUDA runtime compiler; any CUDA 11.2+ copy, for example the nvidia-cuda-nvrtc
// wheel, a CUDA toolkit or PyTorch's) are loaded dynamically, and kernels.cu plus math.hpp, embedded in the
// extension by CMake, are compiled for the GPU that is present with --fmad=false (no multiply-add contraction),
// IEEE division and square root, and no flush-to-zero. The Python layer (etalii_dllm.cuda) finds NVRTC and calls
// initialize().
//
// Weights, activations and the KV cache live on the device as Arrays. Operations queue their kernels on one stream
// without waiting; only a download waits, for the work that produces its data. Callers on several threads take
// turns queueing, and since no kernel's result depends on what else is queued, concurrency cannot change a bit.
#pragma once

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <iterator>
#include <map>
#include <memory>
#include <mutex>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#else
#include <dlfcn.h>
#endif

#include "dllm/quant.hpp"
#include "dllm_cuda_sources.hpp"  // generated by CMake: kCudaKernelsSource, kCudaMathSource

namespace dllm::cuda {

// The few CUDA driver and NVRTC types the backend uses, declared here so no CUDA header is needed.
using CUresult = int;
using CUdevice = int;
using CUdeviceptr = unsigned long long;
using CUcontext = struct CUctx_st*;
using CUmodule = struct CUmod_st*;
using CUfunction = struct CUfunc_st*;
using CUstream = struct CUstream_st*;
using nvrtcResult = int;
using nvrtcProgram = struct _nvrtcProgram*;

constexpr int kAttributeComputeCapabilityMajor = 75;
constexpr int kAttributeComputeCapabilityMinor = 76;

// Headers the device code includes, as tiny stand-ins (NVRTC has no C++ standard library). math.hpp only needs
// size_t, the fixed-width integers, a byte copy and three double constants.
inline const char* const kShimNames[] = {"cmath", "cstddef", "cstdint", "cstring", "limits", "stdexcept"};
inline const char* const kShimSources[] = {
    "#pragma once\n",
    "#pragma once\nnamespace std { typedef unsigned long long size_t; }\n",
    "#pragma once\nnamespace std { typedef signed char int8_t; typedef int int32_t; typedef long long int64_t;\n"
    "typedef unsigned char uint8_t; typedef unsigned int uint32_t; typedef unsigned long long uint64_t; }\n",
    "#pragma once\nnamespace std { inline void* memcpy(void* d, const void* s, unsigned long long n) {\n"
    "unsigned char* o = static_cast<unsigned char*>(d); const unsigned char* i = static_cast<const unsigned char*>(s);\n"
    "for (unsigned long long k = 0; k < n; ++k) { o[k] = i[k]; } return d; } }\n",
    "#pragma once\nnamespace std { template <class T> struct numeric_limits;\n"
    "template <> struct numeric_limits<double> {\n"
    "static double infinity() { return __longlong_as_double(0x7ff0000000000000LL); }\n"
    "static double quiet_NaN() { return __longlong_as_double(0x7ff8000000000000LL); }\n"
    "static double min() { return __longlong_as_double(0x0010000000000000LL); } }; }\n",
    "#pragma once\n",
};

class Library {
public:
    Library() = default;
    Library(const Library&) = delete;
    Library& operator=(const Library&) = delete;

    bool open(const std::string& path) {
#ifdef _WIN32
        // With a full path, the DLL's own directory is searched for its dependencies (nvrtc-builtins).
        const DWORD flags = path.find_first_of("\\/") != std::string::npos ? LOAD_WITH_ALTERED_SEARCH_PATH : 0;
        handle_ = reinterpret_cast<void*>(LoadLibraryExA(path.c_str(), nullptr, flags));
#else
        handle_ = dlopen(path.c_str(), RTLD_NOW | RTLD_LOCAL);
#endif
        return handle_ != nullptr;
    }

    template <typename F>
    F symbol(const char* name) const {
#ifdef _WIN32
        void* address = reinterpret_cast<void*>(GetProcAddress(static_cast<HMODULE>(handle_), name));
#else
        void* address = dlsym(handle_, name);
#endif
        if (address == nullptr) {
            throw std::runtime_error(std::string("CUDA: missing symbol ") + name);
        }
        return reinterpret_cast<F>(address);
    }

private:
    void* handle_ = nullptr;  // never closed: the process keeps the driver loaded
};

struct Driver {
    CUresult (*cuInit)(unsigned int);
    CUresult (*cuDriverGetVersion)(int*);
    CUresult (*cuDeviceGetCount)(int*);
    CUresult (*cuDeviceGet)(CUdevice*, int);
    CUresult (*cuDeviceGetName)(char*, int, CUdevice);
    CUresult (*cuDeviceGetAttribute)(int*, int, CUdevice);
    CUresult (*cuDevicePrimaryCtxRetain)(CUcontext*, CUdevice);
    CUresult (*cuCtxSetCurrent)(CUcontext);
    CUresult (*cuCtxSynchronize)();
    CUresult (*cuModuleLoadData)(CUmodule*, const void*);
    CUresult (*cuModuleGetFunction)(CUfunction*, CUmodule, const char*);
    CUresult (*cuMemAlloc)(CUdeviceptr*, std::size_t);
    CUresult (*cuMemFree)(CUdeviceptr);
    CUresult (*cuMemcpyHtoD)(CUdeviceptr, const void*, std::size_t);
    CUresult (*cuMemcpyDtoH)(void*, CUdeviceptr, std::size_t);
    CUresult (*cuLaunchKernel)(CUfunction, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int,
                               unsigned int, unsigned int, CUstream, void**, void**);
    CUresult (*cuGetErrorString)(CUresult, const char**);
};

struct Nvrtc {
    nvrtcResult (*nvrtcVersion)(int*, int*);
    nvrtcResult (*nvrtcGetNumSupportedArchs)(int*);
    nvrtcResult (*nvrtcGetSupportedArchs)(int*);
    nvrtcResult (*nvrtcCreateProgram)(nvrtcProgram*, const char*, const char*, int, const char* const*,
                                      const char* const*);
    nvrtcResult (*nvrtcCompileProgram)(nvrtcProgram, int, const char* const*);
    nvrtcResult (*nvrtcGetProgramLogSize)(nvrtcProgram, std::size_t*);
    nvrtcResult (*nvrtcGetProgramLog)(nvrtcProgram, char*);
    nvrtcResult (*nvrtcGetCUBINSize)(nvrtcProgram, std::size_t*);
    nvrtcResult (*nvrtcGetCUBIN)(nvrtcProgram, char*);
    nvrtcResult (*nvrtcGetPTXSize)(nvrtcProgram, std::size_t*);
    nvrtcResult (*nvrtcGetPTX)(nvrtcProgram, char*);
    nvrtcResult (*nvrtcDestroyProgram)(nvrtcProgram*);
    const char* (*nvrtcGetErrorString)(nvrtcResult);
};

// The kernels compiled by NVRTC: a cubin (sm_XX) or PTX (compute_XX) image, and what produced it.
struct CompiledKernels {
    std::vector<char> image;
    std::string compiler;
    std::string architecture;
};

// NVRTC, loaded at run time, compiling kernels.cu + math.hpp. Needs no GPU or driver, so CI can check that the
// embedded sources compile (etalii_dllm.cuda.compile_kernels).
class Compiler {
public:
    Compiler() = default;
    Compiler(const Compiler&) = delete;
    Compiler& operator=(const Compiler&) = delete;

    void open(const std::string& nvrtc_path) {
        if (!library_.open(nvrtc_path)) {
            throw std::runtime_error("CUDA: cannot load NVRTC from " + nvrtc_path);
        }
        load_nvrtc();
    }

    // Compiles the kernels to a cubin for the device's architecture when this NVRTC knows it, else to PTX for the
    // newest architecture it knows (the driver then compiles that for the device). Either way every floating point
    // operation is an explicit IEEE round-to-nearest instruction, so the choice cannot change a result.
    CompiledKernels compile(int arch) const {
        int major = 0;
        int minor = 0;
        check_nvrtc(api_.nvrtcVersion(&major, &minor), "nvrtcVersion");
        int count = 0;
        check_nvrtc(api_.nvrtcGetNumSupportedArchs(&count), "nvrtcGetNumSupportedArchs");
        std::vector<int> archs(static_cast<std::size_t>(count));
        check_nvrtc(api_.nvrtcGetSupportedArchs(archs.data()), "nvrtcGetSupportedArchs");
        const bool native = std::find(archs.begin(), archs.end(), arch) != archs.end();
        int target = arch;
        if (!native) {
            target = 0;
            for (int a : archs) {
                if (a <= arch && a > target) {
                    target = a;
                }
            }
            if (target == 0) {
                throw std::runtime_error("CUDA: NVRTC " + std::to_string(major) + "." + std::to_string(minor) +
                                         " cannot compile for compute capability " + std::to_string(arch / 10) + "." +
                                         std::to_string(arch % 10));
            }
        }
        const std::string arch_option =
            std::string(native ? "--gpu-architecture=sm_" : "--gpu-architecture=compute_") + std::to_string(target);
        CompiledKernels result;
        result.compiler = "NVRTC " + std::to_string(major) + "." + std::to_string(minor);
        result.architecture = (native ? "sm_" : "compute_") + std::to_string(target);

        std::vector<const char*> header_sources(std::begin(kShimSources), std::end(kShimSources));
        std::vector<const char*> header_names(std::begin(kShimNames), std::end(kShimNames));
        header_sources.push_back(kCudaMathSource);
        header_names.push_back("dllm/math.hpp");
        nvrtcProgram program = nullptr;
        check_nvrtc(api_.nvrtcCreateProgram(&program, kCudaKernelsSource, "kernels.cu",
                                              static_cast<int>(header_sources.size()), header_sources.data(),
                                              header_names.data()),
                    "nvrtcCreateProgram");
        const char* options[] = {arch_option.c_str(), "--std=c++17", "--device-as-default-execution-space",
                                 "--fmad=false", "--prec-div=true", "--prec-sqrt=true", "--ftz=false"};
        const nvrtcResult compiled =
            api_.nvrtcCompileProgram(program, static_cast<int>(sizeof(options) / sizeof(options[0])), options);
        if (compiled != 0) {
            std::size_t log_size = 0;
            api_.nvrtcGetProgramLogSize(program, &log_size);
            std::string log(log_size, '\0');
            api_.nvrtcGetProgramLog(program, log.data());
            api_.nvrtcDestroyProgram(&program);
            throw std::runtime_error("CUDA: compiling the kernels failed:\n" + log);
        }
        std::size_t size = 0;
        std::vector<char>& image = result.image;
        if (native) {
            check_nvrtc(api_.nvrtcGetCUBINSize(program, &size), "nvrtcGetCUBINSize");
            image.resize(size);
            check_nvrtc(api_.nvrtcGetCUBIN(program, image.data()), "nvrtcGetCUBIN");
        } else {
            check_nvrtc(api_.nvrtcGetPTXSize(program, &size), "nvrtcGetPTXSize");
            image.resize(size);
            check_nvrtc(api_.nvrtcGetPTX(program, image.data()), "nvrtcGetPTX");
        }
        api_.nvrtcDestroyProgram(&program);
        return result;
    }

private:
    void load_nvrtc() {
        api_.nvrtcVersion = library_.symbol<decltype(api_.nvrtcVersion)>("nvrtcVersion");
        api_.nvrtcGetNumSupportedArchs =
            library_.symbol<decltype(api_.nvrtcGetNumSupportedArchs)>("nvrtcGetNumSupportedArchs");
        api_.nvrtcGetSupportedArchs =
            library_.symbol<decltype(api_.nvrtcGetSupportedArchs)>("nvrtcGetSupportedArchs");
        api_.nvrtcCreateProgram = library_.symbol<decltype(api_.nvrtcCreateProgram)>("nvrtcCreateProgram");
        api_.nvrtcCompileProgram =
            library_.symbol<decltype(api_.nvrtcCompileProgram)>("nvrtcCompileProgram");
        api_.nvrtcGetProgramLogSize =
            library_.symbol<decltype(api_.nvrtcGetProgramLogSize)>("nvrtcGetProgramLogSize");
        api_.nvrtcGetProgramLog = library_.symbol<decltype(api_.nvrtcGetProgramLog)>("nvrtcGetProgramLog");
        api_.nvrtcGetCUBINSize = library_.symbol<decltype(api_.nvrtcGetCUBINSize)>("nvrtcGetCUBINSize");
        api_.nvrtcGetCUBIN = library_.symbol<decltype(api_.nvrtcGetCUBIN)>("nvrtcGetCUBIN");
        api_.nvrtcGetPTXSize = library_.symbol<decltype(api_.nvrtcGetPTXSize)>("nvrtcGetPTXSize");
        api_.nvrtcGetPTX = library_.symbol<decltype(api_.nvrtcGetPTX)>("nvrtcGetPTX");
        api_.nvrtcDestroyProgram =
            library_.symbol<decltype(api_.nvrtcDestroyProgram)>("nvrtcDestroyProgram");
        api_.nvrtcGetErrorString =
            library_.symbol<decltype(api_.nvrtcGetErrorString)>("nvrtcGetErrorString");
    }

    void check_nvrtc(nvrtcResult result, const char* call) const {
        if (result != 0) {
            throw std::runtime_error(std::string("CUDA: ") + call + " failed: " + api_.nvrtcGetErrorString(result));
        }
    }

    Library library_;
    Nvrtc api_{};
};

class Runtime {
public:
    // Never destroyed: device memory owned by Python objects may be released during interpreter shutdown.
    static Runtime& instance() {
        static Runtime* runtime = new Runtime();
        return *runtime;
    }

    bool ready() const { return ready_; }
    const std::string& device_name() const { return device_name_; }
    const std::string& compiler() const { return compiler_; }
    const std::string& architecture() const { return architecture_; }
    int device_index() const { return device_index_; }

    static int device_count() {
        Library library;
        if (!library.open(driver_library())) {
            return 0;
        }
        auto init = library.symbol<CUresult (*)(unsigned int)>("cuInit");
        auto count_fn = library.symbol<CUresult (*)(int*)>("cuDeviceGetCount");
        int count = 0;
        if (init(0) != 0 || count_fn(&count) != 0) {
            return 0;
        }
        return count;
    }

    enum Function : std::size_t {
        kLinear,
        kLinearQ8,
        kQuantizeQ8,
        kRmsNorm,
        kActivation,
        kSwiglu,
        kAdd,
        kCopy,
        kRope,
        kAttention,
        kFunctionCount
    };

    // Loads the driver and nvrtc_path, and compiles the kernels for device `index`. Only the first call does work;
    // later calls must name the same device.
    void initialize(const std::string& nvrtc_path, int index) {
        std::lock_guard<std::mutex> lock(mutex_);
        if (ready_) {
            if (index != device_index_) {
                throw std::runtime_error("CUDA: the backend is already running on device " +
                                         std::to_string(device_index_));
            }
            return;
        }
        if (!driver_library_.open(driver_library())) {
            throw std::runtime_error(std::string("CUDA: cannot load the NVIDIA driver (") + driver_library() + ")");
        }
        load_driver();
        check(driver_.cuInit(0), "cuInit");
        int count = 0;
        check(driver_.cuDeviceGetCount(&count), "cuDeviceGetCount");
        if (index < 0 || index >= count) {
            throw std::runtime_error("CUDA: no device " + std::to_string(index) + " (" + std::to_string(count) +
                                     " found)");
        }
        check(driver_.cuDeviceGet(&device_, index), "cuDeviceGet");
        char name[256] = {};
        check(driver_.cuDeviceGetName(name, sizeof(name) - 1, device_), "cuDeviceGetName");
        int major = 0;
        int minor = 0;
        check(driver_.cuDeviceGetAttribute(&major, kAttributeComputeCapabilityMajor, device_), "cuDeviceGetAttribute");
        check(driver_.cuDeviceGetAttribute(&minor, kAttributeComputeCapabilityMinor, device_), "cuDeviceGetAttribute");
        check(driver_.cuDevicePrimaryCtxRetain(&context_, device_), "cuDevicePrimaryCtxRetain");
        check(driver_.cuCtxSetCurrent(context_), "cuCtxSetCurrent");

        nvrtc_.open(nvrtc_path);
        const CompiledKernels kernels = nvrtc_.compile(major * 10 + minor);
        check(driver_.cuModuleLoadData(&module_, kernels.image.data()), "cuModuleLoadData");
        const char* names[kFunctionCount] = {"linear_f32", "linear_q8", "quantize_q8", "rms_norm", "activation",
                                             "swiglu",     "add",       "copy_words",  "rope",     "attention"};
        for (std::size_t i = 0; i < kFunctionCount; ++i) {
            check(driver_.cuModuleGetFunction(&functions_[i], module_, names[i]), "cuModuleGetFunction");
        }
        device_index_ = index;
        device_name_ = name;
        compiler_ = kernels.compiler;
        architecture_ = kernels.architecture;
        ready_ = true;
    }

    // Kernels are queued on one stream (the context's default stream), one caller at a time: every operation holds
    // this lock while it queues its work. The stream runs the work in queue order, so an operation always sees the
    // finished results of the ones queued before it.
    std::unique_lock<std::mutex> acquire() {
        std::unique_lock<std::mutex> lock(mutex_);
        if (!ready_) {
            throw std::runtime_error("CUDA: the backend is not initialised (etalii_dllm.cuda.initialize())");
        }
        check(driver_.cuCtxSetCurrent(context_), "cuCtxSetCurrent");
        return lock;
    }

    // Device memory comes from a pool of power-of-two blocks that are reused, never returned to the driver: work is
    // queued without waiting, and a freed block is only reused by work queued later on the same stream.
    std::pair<CUdeviceptr, std::size_t> take(std::size_t bytes) {
        std::size_t capacity = 256;
        while (capacity < bytes) {
            capacity *= 2;
        }
        {
            std::lock_guard<std::mutex> lock(pool_mutex_);
            auto& blocks = pool_[capacity];
            if (!blocks.empty()) {
                const CUdeviceptr pointer = blocks.back();
                blocks.pop_back();
                return {pointer, capacity};
            }
        }
        CUdeviceptr pointer = 0;
        check(driver_.cuMemAlloc(&pointer, capacity), "cuMemAlloc");
        return {pointer, capacity};
    }

    void give(CUdeviceptr pointer, std::size_t capacity) noexcept {
        std::lock_guard<std::mutex> lock(pool_mutex_);
        pool_[capacity].push_back(pointer);
    }

    // Synchronous copies: a copy from host memory waits for the queued work first, a copy to the host waits for
    // the work that produces its data.
    void upload(CUdeviceptr destination, const void* source, std::size_t bytes) {
        if (bytes != 0) {
            check(driver_.cuMemcpyHtoD(destination, source, bytes), "cuMemcpyHtoD");
        }
    }

    void download(void* destination, CUdeviceptr source, std::size_t bytes) {
        if (bytes != 0) {
            check(driver_.cuMemcpyDtoH(destination, source, bytes), "cuMemcpyDtoH");
        }
    }

    void launch(Function function, unsigned grid_x, unsigned grid_y, unsigned block, void** arguments) {
        if (grid_x == 0 || grid_y == 0) {
            return;
        }
        check(driver_.cuLaunchKernel(functions_[function], grid_x, grid_y, 1, block, 1, 1, 0, nullptr, arguments,
                                     nullptr),
              "cuLaunchKernel");
    }

    void check(CUresult result, const char* call) const {
        if (result == 0) {
            return;
        }
        const char* message = nullptr;
        if (driver_.cuGetErrorString != nullptr) {
            driver_.cuGetErrorString(result, &message);
        }
        throw std::runtime_error(std::string("CUDA: ") + call + " failed (" + std::to_string(result) +
                                 (message != nullptr ? std::string(": ") + message : std::string()) + ")");
    }

private:
    Runtime() = default;

    static const char* driver_library() {
#ifdef _WIN32
        return "nvcuda.dll";
#else
        return "libcuda.so.1";
#endif
    }

    void load_driver() {
        driver_.cuInit = driver_library_.symbol<decltype(driver_.cuInit)>("cuInit");
        driver_.cuDriverGetVersion = driver_library_.symbol<decltype(driver_.cuDriverGetVersion)>("cuDriverGetVersion");
        driver_.cuDeviceGetCount = driver_library_.symbol<decltype(driver_.cuDeviceGetCount)>("cuDeviceGetCount");
        driver_.cuDeviceGet = driver_library_.symbol<decltype(driver_.cuDeviceGet)>("cuDeviceGet");
        driver_.cuDeviceGetName = driver_library_.symbol<decltype(driver_.cuDeviceGetName)>("cuDeviceGetName");
        driver_.cuDeviceGetAttribute =
            driver_library_.symbol<decltype(driver_.cuDeviceGetAttribute)>("cuDeviceGetAttribute");
        driver_.cuDevicePrimaryCtxRetain =
            driver_library_.symbol<decltype(driver_.cuDevicePrimaryCtxRetain)>("cuDevicePrimaryCtxRetain");
        driver_.cuCtxSetCurrent = driver_library_.symbol<decltype(driver_.cuCtxSetCurrent)>("cuCtxSetCurrent");
        driver_.cuCtxSynchronize = driver_library_.symbol<decltype(driver_.cuCtxSynchronize)>("cuCtxSynchronize");
        driver_.cuModuleLoadData = driver_library_.symbol<decltype(driver_.cuModuleLoadData)>("cuModuleLoadData");
        driver_.cuModuleGetFunction =
            driver_library_.symbol<decltype(driver_.cuModuleGetFunction)>("cuModuleGetFunction");
        driver_.cuMemAlloc = driver_library_.symbol<decltype(driver_.cuMemAlloc)>("cuMemAlloc_v2");
        driver_.cuMemFree = driver_library_.symbol<decltype(driver_.cuMemFree)>("cuMemFree_v2");
        driver_.cuMemcpyHtoD = driver_library_.symbol<decltype(driver_.cuMemcpyHtoD)>("cuMemcpyHtoD_v2");
        driver_.cuMemcpyDtoH = driver_library_.symbol<decltype(driver_.cuMemcpyDtoH)>("cuMemcpyDtoH_v2");
        driver_.cuLaunchKernel = driver_library_.symbol<decltype(driver_.cuLaunchKernel)>("cuLaunchKernel");
        driver_.cuGetErrorString = driver_library_.symbol<decltype(driver_.cuGetErrorString)>("cuGetErrorString");
    }

    std::mutex mutex_;
    std::mutex pool_mutex_;
    std::map<std::size_t, std::vector<CUdeviceptr>> pool_;
    bool ready_ = false;
    Library driver_library_;
    Compiler nvrtc_;
    Driver driver_{};
    CUdevice device_ = 0;
    CUcontext context_ = nullptr;
    CUmodule module_ = nullptr;
    CUfunction functions_[kFunctionCount] = {};
    int device_index_ = -1;
    std::string device_name_;
    std::string compiler_;
    std::string architecture_;
};

// Device memory shared by the arrays that view it; returned to the pool when the last one goes away.
struct Storage {
    CUdeviceptr pointer;
    std::size_t capacity;
    Storage(CUdeviceptr p, std::size_t c) : pointer(p), capacity(c) {}
    Storage(const Storage&) = delete;
    Storage& operator=(const Storage&) = delete;
    ~Storage() { Runtime::instance().give(pointer, capacity); }
};

// A byte range of device memory: a weight, an activation, a KV cache. Views share their storage.
class Array {
public:
    Array() = default;
    explicit Array(std::size_t bytes) : bytes_(bytes) {
        auto [pointer, capacity] = Runtime::instance().take(bytes);
        storage_ = std::make_shared<Storage>(pointer, capacity);
    }

    CUdeviceptr pointer() const { return storage_->pointer + offset_; }
    std::size_t bytes() const { return bytes_; }

    Array view(std::size_t offset, std::size_t bytes) const {
        if (offset + bytes > bytes_) {
            throw std::out_of_range("CUDA: view outside the array");
        }
        Array result = *this;
        result.offset_ += offset;
        result.bytes_ = bytes;
        return result;
    }

private:
    std::shared_ptr<Storage> storage_;
    std::size_t offset_ = 0;
    std::size_t bytes_ = 0;
};

namespace detail {

constexpr unsigned kBlock = 128;
// linear runs one thread per output; small blocks spread few outputs (a decode step) over more multiprocessors.
constexpr unsigned kLinearBlock = 32;
constexpr std::size_t kMaxGridY = 65535;

inline unsigned blocks_for(std::size_t n, unsigned block = kBlock) {
    const std::size_t blocks = (n + block - 1) / block;
    return static_cast<unsigned>(std::min<std::size_t>(blocks, std::size_t(1) << 20));
}

inline unsigned row_grid(std::size_t rows) { return static_cast<unsigned>(std::min(rows, kMaxGridY)); }

inline void require(bool condition, const char* message) {
    if (!condition) {
        throw std::invalid_argument(message);
    }
}

inline CUdeviceptr pointer_or_null(const Array* array) { return array != nullptr ? array->pointer() : 0; }

}  // namespace detail

inline Array upload(const void* data, std::size_t bytes) {
    Runtime& runtime = Runtime::instance();
    auto lock = runtime.acquire();
    Array array(bytes);
    runtime.upload(array.pointer(), data, bytes);
    return array;
}

inline Array empty(std::size_t bytes) {
    Runtime& runtime = Runtime::instance();
    auto lock = runtime.acquire();
    return Array(bytes);
}

inline void download(const Array& array, void* destination) {
    Runtime& runtime = Runtime::instance();
    auto lock = runtime.acquire();
    runtime.download(destination, array.pointer(), array.bytes());
}

// Copies src into dst (same size, a multiple of 4 bytes), in stream order.
inline void copy(const Array& source, const Array& destination) {
    detail::require(source.bytes() == destination.bytes() && source.bytes() % 4 == 0, "copy: sizes do not match");
    Runtime& runtime = Runtime::instance();
    auto lock = runtime.acquire();
    CUdeviceptr s = source.pointer();
    CUdeviceptr d = destination.pointer();
    unsigned long long words = source.bytes() / 4;
    void* arguments[] = {&s, &d, &words};
    runtime.launch(Runtime::kCopy, detail::blocks_for(words), 1, detail::kBlock, arguments);
}

// Transposes w[out][in] into wt[in][out], the layout of the linear kernel.
inline std::vector<float> transpose_linear(const float* w, std::size_t in_features, std::size_t out_features) {
    std::vector<float> wt(in_features * out_features);
    for (std::size_t n = 0; n < out_features; ++n) {
        for (std::size_t k = 0; k < in_features; ++k) {
            wt[k * out_features + n] = w[n * in_features + k];
        }
    }
    return wt;
}

// out[rows][out_features] = linear(x, w) (+ bias) with wt = transpose_linear(w). Bit-identical to linear().
inline Array linear(const Array& x, std::size_t rows, std::size_t in_features, const Array& wt,
                    std::size_t out_features, const Array* bias) {
    detail::require(x.bytes() == rows * in_features * sizeof(float), "linear: x does not match rows and in_features");
    detail::require(wt.bytes() == in_features * out_features * sizeof(float), "linear: weight does not match");
    detail::require(bias == nullptr || bias->bytes() == out_features * sizeof(float), "linear: bias does not match");
    Runtime& runtime = Runtime::instance();
    auto lock = runtime.acquire();
    Array out(rows * out_features * sizeof(float));
    CUdeviceptr dx = x.pointer();
    CUdeviceptr dw = wt.pointer();
    CUdeviceptr db = detail::pointer_or_null(bias);
    CUdeviceptr dout = out.pointer();
    unsigned long long r = rows;
    unsigned long long k = in_features;
    unsigned long long n = out_features;
    void* arguments[] = {&dx, &dw, &db, &dout, &r, &k, &n};
    runtime.launch(Runtime::kLinear, detail::blocks_for(out_features, detail::kLinearBlock), detail::row_grid(rows),
                   detail::kLinearBlock, arguments);
    return out;
}

// Rearranges Q8_0 weights wq[out][in], ws[out][in / 32] into the block-major device layout of kernels.cu:
// values [in / 32][out][32] followed by scales [in / 32][out] (as bytes).
inline std::vector<std::uint8_t> pack_q8(const std::int8_t* wq, const float* ws, std::size_t in_features,
                                         std::size_t out_features) {
    const std::size_t blocks = in_features / kQ8Block;
    std::vector<std::uint8_t> packed(blocks * out_features * (kQ8Block + sizeof(float)));
    std::uint8_t* values = packed.data();
    std::uint8_t* scales = packed.data() + blocks * out_features * kQ8Block;
    for (std::size_t n = 0; n < out_features; ++n) {
        for (std::size_t b = 0; b < blocks; ++b) {
            std::memcpy(values + (b * out_features + n) * kQ8Block, wq + n * in_features + b * kQ8Block, kQ8Block);
            std::memcpy(scales + (b * out_features + n) * sizeof(float), ws + n * blocks + b, sizeof(float));
        }
    }
    return packed;
}

// Q8_0 linear with a pack_q8() weight: the activations are quantised on the device by the rule of quantize_q8_0,
// then combined as linear_q8() does. Bit-identical to linear_q8().
inline Array linear_q8(const Array& x, std::size_t rows, std::size_t in_features, const Array& packed,
                       std::size_t out_features, const Array* bias) {
    detail::require(in_features % kQ8Block == 0, "Q8_0 needs in_features to be a multiple of 32");
    detail::require(x.bytes() == rows * in_features * sizeof(float), "linear: x does not match rows and in_features");
    const std::size_t blocks = in_features / kQ8Block;
    detail::require(packed.bytes() == blocks * out_features * (kQ8Block + sizeof(float)), "linear: weight mismatch");
    detail::require(bias == nullptr || bias->bytes() == out_features * sizeof(float), "linear: bias does not match");
    Runtime& runtime = Runtime::instance();
    auto lock = runtime.acquire();
    Array xq(rows * in_features);
    Array xs(rows * blocks * sizeof(float));
    Array out(rows * out_features * sizeof(float));
    CUdeviceptr dx = x.pointer();
    CUdeviceptr dxq = xq.pointer();
    CUdeviceptr dxs = xs.pointer();
    unsigned long long r = rows;
    unsigned long long k = in_features;
    void* quantize[] = {&dx, &dxq, &dxs, &r, &k};
    runtime.launch(Runtime::kQuantizeQ8, detail::blocks_for(rows * blocks), 1, detail::kBlock, quantize);
    CUdeviceptr dwq = packed.pointer();
    CUdeviceptr dws = packed.pointer() + blocks * out_features * kQ8Block;
    CUdeviceptr db = detail::pointer_or_null(bias);
    CUdeviceptr dout = out.pointer();
    unsigned long long n = out_features;
    void* arguments[] = {&dxq, &dxs, &dwq, &dws, &db, &dout, &r, &k, &n};
    runtime.launch(Runtime::kLinearQ8, detail::blocks_for(out_features, detail::kLinearBlock), detail::row_grid(rows),
                   detail::kLinearBlock, arguments);
    return out;
}

inline Array rms_norm(const Array& x, std::size_t rows, std::size_t dim, const Array* weight, double eps,
                      bool add_unit_offset) {
    detail::require(x.bytes() == rows * dim * sizeof(float), "rms_norm: x does not match rows and dim");
    detail::require(weight == nullptr || weight->bytes() == dim * sizeof(float), "rms_norm: weight does not match");
    Runtime& runtime = Runtime::instance();
    auto lock = runtime.acquire();
    Array out(x.bytes());
    CUdeviceptr dw = detail::pointer_or_null(weight);
    unsigned long long d = dim;
    int unit = add_unit_offset ? 1 : 0;
    // One block per row; rows are independent, so long inputs simply run in slices of rows.
    for (std::size_t r0 = 0; r0 < rows; r0 += detail::kMaxGridY) {
        CUdeviceptr dx = x.pointer() + r0 * dim * sizeof(float);
        CUdeviceptr dout = out.pointer() + r0 * dim * sizeof(float);
        void* arguments[] = {&dx, &dw, &dout, &d, &eps, &unit};
        runtime.launch(Runtime::kRmsNorm, detail::row_grid(rows - r0), 1, detail::kBlock, arguments);
    }
    return out;
}

// kind: 0 silu, 1 gelu, 2 gelu_tanh.
inline Array activation(const Array& x, int kind) {
    detail::require(x.bytes() % sizeof(float) == 0 && kind >= 0 && kind <= 2, "activation: bad arguments");
    Runtime& runtime = Runtime::instance();
    auto lock = runtime.acquire();
    Array out(x.bytes());
    CUdeviceptr dx = x.pointer();
    CUdeviceptr dout = out.pointer();
    unsigned long long n = x.bytes() / sizeof(float);
    void* arguments[] = {&dx, &dout, &n, &kind};
    runtime.launch(Runtime::kActivation, detail::blocks_for(n), 1, detail::kBlock, arguments);
    return out;
}

// float(silu(gate)) * up, elementwise in float32 (the SwiGLU product of the decoder).
inline Array swiglu(const Array& gate, const Array& up) {
    detail::require(gate.bytes() == up.bytes() && gate.bytes() % sizeof(float) == 0, "swiglu: sizes do not match");
    Runtime& runtime = Runtime::instance();
    auto lock = runtime.acquire();
    Array out(gate.bytes());
    CUdeviceptr dg = gate.pointer();
    CUdeviceptr du = up.pointer();
    CUdeviceptr dout = out.pointer();
    unsigned long long n = gate.bytes() / sizeof(float);
    void* arguments[] = {&dg, &du, &dout, &n};
    runtime.launch(Runtime::kSwiglu, detail::blocks_for(n), 1, detail::kBlock, arguments);
    return out;
}

// a + b, elementwise in float32 (the residual additions).
inline Array add(const Array& a, const Array& b) {
    detail::require(a.bytes() == b.bytes() && a.bytes() % sizeof(float) == 0, "add: sizes do not match");
    Runtime& runtime = Runtime::instance();
    auto lock = runtime.acquire();
    Array out(a.bytes());
    CUdeviceptr da = a.pointer();
    CUdeviceptr db = b.pointer();
    CUdeviceptr dout = out.pointer();
    unsigned long long n = a.bytes() / sizeof(float);
    void* arguments[] = {&da, &db, &dout, &n};
    runtime.launch(Runtime::kAdd, detail::blocks_for(n), 1, detail::kBlock, arguments);
    return out;
}

// x [tokens][heads][head_dim] float, positions [tokens] int64, inv_freq [rotary_dim / 2] double.
inline Array rope(const Array& x, const Array& positions, const Array& inv_freq, std::size_t tokens,
                  std::size_t heads, std::size_t head_dim, bool interleaved, bool inverse) {
    const std::size_t rotary_dim = 2 * (inv_freq.bytes() / sizeof(double));
    detail::require(x.bytes() == tokens * heads * head_dim * sizeof(float), "rope: x does not match its shape");
    detail::require(positions.bytes() == tokens * sizeof(std::int64_t), "rope: one position per token");
    detail::require(rotary_dim <= head_dim, "rope: 2 * len(inv_freq) must not exceed head_dim");
    Runtime& runtime = Runtime::instance();
    auto lock = runtime.acquire();
    Array out(x.bytes());
    CUdeviceptr dx = x.pointer();
    CUdeviceptr dp = positions.pointer();
    CUdeviceptr df = inv_freq.pointer();
    CUdeviceptr dout = out.pointer();
    unsigned long long t = tokens;
    unsigned long long h = heads;
    unsigned long long d = head_dim;
    unsigned long long rd = rotary_dim;
    int inter = interleaved ? 1 : 0;
    int inv = inverse ? 1 : 0;
    void* arguments[] = {&dx, &dp, &df, &dout, &t, &h, &d, &rd, &inter, &inv};
    const std::size_t work = tokens * heads * (rotary_dim / 2 + head_dim - rotary_dim);
    runtime.launch(Runtime::kRope, detail::blocks_for(work), 1, detail::kBlock, arguments);
    return out;
}

// Rows of scores kept on the device at once; rows are independent, so the slicing never changes a result.
constexpr std::size_t kAttentionScratchDoubles = std::size_t(1) << 23;  // 64 MiB

// q [q_len][q_heads][head_dim], k [>= kv_len][kv_heads][head_dim], v [>= kv_len][kv_heads][value_dim]: only the
// first kv_len keys and values are read.
inline Array attention(const Array& q, const Array& k, const Array& v, std::size_t q_len, std::size_t kv_len,
                       std::size_t q_heads, std::size_t kv_heads, std::size_t head_dim, std::size_t value_dim,
                       double scale, bool causal, std::size_t q_offset, std::size_t window = 0) {
    detail::require(kv_heads > 0 && q_heads % kv_heads == 0, "q_heads must be a multiple of kv_heads");
    detail::require(q.bytes() == q_len * q_heads * head_dim * sizeof(float), "attention: q does not match its shape");
    detail::require(k.bytes() >= kv_len * kv_heads * head_dim * sizeof(float), "attention: k is too short");
    detail::require(v.bytes() >= kv_len * kv_heads * value_dim * sizeof(float), "attention: v is too short");
    Runtime& runtime = Runtime::instance();
    auto lock = runtime.acquire();
    const std::size_t rows = q_len * q_heads;
    Array out(rows * value_dim * sizeof(float));
    const std::size_t keys = std::max<std::size_t>(kv_len, 1);
    const std::size_t per_launch = std::max<std::size_t>(1, std::min(detail::kMaxGridY, kAttentionScratchDoubles / keys));
    Array scratch(std::min(per_launch, std::max<std::size_t>(rows, 1)) * keys * sizeof(double));
    CUdeviceptr dq = q.pointer();
    CUdeviceptr dk = k.pointer();
    CUdeviceptr dv = v.pointer();
    CUdeviceptr dout = out.pointer();
    CUdeviceptr dscratch = scratch.pointer();
    unsigned long long kl = kv_len;
    unsigned long long qh = q_heads;
    unsigned long long kh = kv_heads;
    unsigned long long hd = head_dim;
    unsigned long long vd = value_dim;
    int c = causal ? 1 : 0;
    unsigned long long offset = q_offset;
    unsigned long long w = window;
    for (std::size_t row0 = 0; row0 < rows; row0 += per_launch) {
        unsigned long long first = row0;
        void* arguments[] = {&dq, &dk, &dv, &dout, &dscratch, &first, &kl, &qh, &kh, &hd, &vd, &scale, &c, &offset, &w};
        runtime.launch(Runtime::kAttention, static_cast<unsigned>(std::min(per_launch, rows - row0)), 1,
                       detail::kBlock, arguments);
    }
    return out;
}

}  // namespace dllm::cuda
